# Generated by Django 3.1.2 on 2020-10-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('display', models.BooleanField(default=False)),
                ('display_in_homeimage', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='categoria/')),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('hex_code', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('display', models.BooleanField(default=False)),
                ('display_in_home', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_discount', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('modified', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto')),
            ],
            options={
                'verbose_name': 'ImageOptional',
                'verbose_name_plural': 'ImageOptionals',
            },
        ),
    ]
